/**
 * EDI 945 (Warehouse Shipping Advice) Generation Service
 *
 * Generated by the 3PL warehouse to confirm to a depositor (brand / shipper)
 * what was actually picked, packed, and shipped against a prior 940 Warehouse
 * Shipping Order.
 *
 * Typical segment structure:
 *   W06  - Warehouse Shipping Advice header (reporting code, depositor order #,
 *          ship date, shipper ID, received # or PO)
 *   N1*  - Names loop (ST, SF, WH, carrier)
 *   N3 / N4 - Address lines
 *   G62  - Actual ship date (qualifier 11)
 *   NTE  - Free-form notes
 *   W27  - Carrier details (transportation method, SCAC, routing, tracking)
 *   LX   - Line number
 *   W12  - Item detail (qty shipped / ordered, UOM, item qualifier, SKU, lot, marks)
 *   G69  - Line description
 *   N9   - Line-level reference (tracking number per line, customer ref)
 *   W03  - Total shipment information (total qty shipped, weight, pallet count)
 */

import { X12EnvelopeBuilder } from './edi/X12EnvelopeBuilder.js';
import { EdiOperationResult } from './edi/types.js';

export interface EDI945LineData {
  lineNumber: number;
  sku: string;
  /** Quantity actually shipped */
  shippedQuantity: number;
  /** Quantity originally ordered on the 940 */
  orderedQuantity: number;
  uomCode?: string;           // default 'EA'
  lotNumber?: string;
  description?: string;
  customerLineRef?: string;
  trackingNumber?: string;
}

export interface EDI945Address {
  name: string;
  partyQualifier: 'ST' | 'SF' | 'WH' | 'DE' | 'BY' | string;
  idCode?: string;
  address1?: string;
  address2?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
}

export interface EDI945Data {
  /** W06-02 depositor order number (echoes back the 940 reference) */
  depositorOrderNumber: string;
  /** W06-04 shipper ID (typically our warehouse ID) */
  shipperId?: string;
  /** W06-05 purchase order number (if different from depositor order) */
  purchaseOrderNumber?: string;
  /** Actual ship date */
  shipDate: Date;
  /** W06-01 reporting code - N = New (default), C = Cancellation, R = Replacement */
  reportingCode?: 'N' | 'C' | 'R';

  addresses: EDI945Address[];

  lines: EDI945LineData[];

  /** Optional shipment-level carrier / routing info for W27 */
  carrier?: {
    scac?: string;
    transportationMethodCode?: string;     // e.g. 'M' motor, 'A' air
    routing?: string;
    bolNumber?: string;
    trackingNumber?: string;
  };

  /** Total shipment weight in grams (emits W03 with weight) */
  totalWeightGrams?: number;
  /** Total pallet count */
  totalPallets?: number;

  /** Free-text notes (appears as NTE) */
  notes?: string;
}

export interface EDI945Config {
  senderId?: string;
  receiverId?: string;
  interchangeControlNumber?: string;
}

export interface IEDI945Service {
  generateEDI945(data: EDI945Data, config?: EDI945Config): string;
  validateAndGenerate(data: EDI945Data, config?: EDI945Config): EdiOperationResult<string>;
}

export class EDI945Service implements IEDI945Service {
  private envelope = new X12EnvelopeBuilder();

  validateAndGenerate(data: EDI945Data, config?: EDI945Config): EdiOperationResult<string> {
    const errors: string[] = [];
    const warnings: string[] = [];

    if (!data.depositorOrderNumber) errors.push('depositorOrderNumber is required');
    if (!data.shipDate) errors.push('shipDate is required');
    if (!data.addresses || data.addresses.length === 0) errors.push('At least one address is required');
    if (!data.addresses?.some(a => a.partyQualifier === 'ST')) errors.push('Ship-to (ST) address is required');
    if (!data.lines || data.lines.length === 0) errors.push('At least one line is required');

    for (const [idx, line] of (data.lines ?? []).entries()) {
      if (!line.sku) errors.push(`Line ${idx + 1}: sku is required`);
      if (line.shippedQuantity < 0) errors.push(`Line ${idx + 1}: shippedQuantity cannot be negative`);
      if (line.orderedQuantity < 1) errors.push(`Line ${idx + 1}: orderedQuantity must be positive`);
      if (line.shippedQuantity > line.orderedQuantity) {
        warnings.push(`Line ${idx + 1}: shipped ${line.shippedQuantity} exceeds ordered ${line.orderedQuantity}`);
      }
    }

    if (errors.length > 0) return { success: false, errors, warnings };

    try {
      const content = this.generateEDI945(data, config);
      return { success: true, data: content, errors: [], warnings };
    } catch (err) {
      return { success: false, errors: [`Generation failed: ${(err as Error).message}`], warnings };
    }
  }

  generateEDI945(data: EDI945Data, config?: EDI945Config): string {
    const e = this.envelope.e;
    const senderId = config?.senderId || 'OPENTMS';
    const receiverId = config?.receiverId || 'DEPOSITOR';
    const reportingCode = data.reportingCode || 'N';
    const body: string[] = [];

    // W06 - Warehouse Shipping Advice header
    // W06*reportingCode*depositorOrderNumber*shipDate*shipperId*PONumber
    body.push(
      `W06${e}${reportingCode}${e}${data.depositorOrderNumber}${e}${this.envelope.formatDateLong(data.shipDate)}${e}${data.shipperId || senderId}${e}${data.purchaseOrderNumber || ''}`,
    );

    // N1 address loops
    for (const addr of data.addresses) {
      body.push(
        `N1${e}${addr.partyQualifier}${e}${this.envelope.sanitize(addr.name, 60)}${e}${addr.idCode ? '92' : ''}${e}${addr.idCode || ''}`,
      );
      if (addr.address1) body.push(`N3${e}${this.envelope.sanitize(addr.address1, 55)}`);
      if (addr.city || addr.state || addr.postalCode || addr.country) {
        const n4 = [
          this.envelope.sanitize(addr.city || '', 30),
          addr.state || '',
          addr.postalCode || '',
          addr.country || '',
        ];
        body.push(`N4${e}${n4.join(e)}`);
      }
    }

    // G62 - actual ship date
    body.push(`G62${e}11${e}${this.envelope.formatDateLong(data.shipDate)}`);

    // NTE - notes
    if (data.notes) {
      body.push(`NTE${e}${e}${this.envelope.sanitize(data.notes, 80)}`);
    }

    // W27 - carrier details
    if (data.carrier?.scac || data.carrier?.trackingNumber || data.carrier?.bolNumber) {
      const w27 = [
        data.carrier.transportationMethodCode || 'M',
        data.carrier.scac || '',
        data.carrier.routing || '',
        data.carrier.bolNumber || '',
        data.carrier.trackingNumber || '',
      ];
      body.push(`W27${e}${w27.join(e)}`);
    }

    // Lines
    for (const line of data.lines) {
      // LX - Line number
      body.push(`LX${e}${line.lineNumber}`);

      // W12 - Item detail
      // W12*shipmentOrderStatusCode*qtyOrdered*qtyShipped*qtyBackordered*UOM*itemQualifier*itemNumber*...*lotNumber
      const statusCode = line.shippedQuantity === 0 ? 'CN'
        : line.shippedQuantity < line.orderedQuantity ? 'PC'  // partial
        : 'CC'; // complete
      const backordered = Math.max(0, line.orderedQuantity - line.shippedQuantity);
      const uom = line.uomCode || 'EA';
      const w12Parts = [
        statusCode,
        String(line.orderedQuantity),
        String(line.shippedQuantity),
        String(backordered),
        uom,
        '', '', 'VP', line.sku,
      ];
      body.push(`W12${e}${w12Parts.join(e)}`);

      // G69 - description
      if (line.description) {
        body.push(`G69${e}${this.envelope.sanitize(line.description, 45)}`);
      }

      // N9 - line-level references
      if (line.trackingNumber) {
        body.push(`N9${e}CN${e}${line.trackingNumber}`);
      }
      if (line.lotNumber) {
        body.push(`N9${e}LT${e}${line.lotNumber}`);
      }
      if (line.customerLineRef) {
        body.push(`N9${e}PD${e}${line.customerLineRef}`);
      }
    }

    // W03 - Totals
    const totalShipped = data.lines.reduce((t, l) => t + l.shippedQuantity, 0);
    const w03Parts = [
      String(totalShipped),
      data.totalWeightGrams != null ? String(Math.round(data.totalWeightGrams / 1000)) : '',   // kg
      data.totalWeightGrams != null ? 'KG' : '',
      data.totalPallets != null ? String(data.totalPallets) : '',
    ];
    body.push(`W03${e}${w03Parts.join(e)}`);

    return this.envelope.wrap(body, {
      senderId,
      receiverId,
      functionalIdentifier: 'SW',
      transactionType: '945',
      controlNumber: config?.interchangeControlNumber,
    });
  }
}
