import { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { container, TOKENS } from '../di/index.js';
import { WAREHOUSE_SCOPE_QUERY, WAREHOUSE_SCOPE_ONE_OF, warehouseScopeFrom } from '../repositories/warehouseScope.js';
import { ICommandBus } from '../commands/CommandBus.js';
import { CREATE_LOAD_PLAN } from '../commands/warehouse/CreateLoadPlanCommand.js';
import { COMPLETE_LOAD_PLAN } from '../commands/warehouse/CompleteLoadPlanCommand.js';
import { ILoadPlanRepository } from '../repositories/LoadPlanRepository.js';
import crypto from 'crypto';
import { registerWmsGuard } from '../auth/wmsGuard.js';

export async function loadPlanRoutes(server: FastifyInstance) {
  // WMS permission guard (#134): wms:read for reads, wms:write for mutations
  await registerWmsGuard(server);

  const commandBus = container.resolve<ICommandBus>(TOKENS.ICommandBus);
  const repo = container.resolve<ILoadPlanRepository>(TOKENS.ILoadPlanRepository);

  // GET /api/v1/load-plans?locationId=xxx&status=xxx
  server.get('/api/v1/load-plans', {
    schema: {
      tags: ['WMS - Load Planning'],
      summary: 'List load plans',
      querystring: {
        type: 'object', oneOf: WAREHOUSE_SCOPE_ONE_OF,
        properties: {
          ...WAREHOUSE_SCOPE_QUERY,
          status: { type: 'string' },
        },
      },
    },
  }, async (req: FastifyRequest) => {
    const q = req.query as { facilityId?: string; locationId?: string; status?: string };
    const plans = await repo.find(req.orgId!, warehouseScopeFrom(q), q.status);

    return { data: plans, error: null };
  });

  // GET /api/v1/load-plans/:id
  server.get('/api/v1/load-plans/:id', {
    schema: { tags: ['WMS - Load Planning'], summary: 'Get load plan detail with lines' },
  }, async (req: FastifyRequest, reply: FastifyReply) => {
    const { id } = req.params as { id: string };
    // A cross-tenant id misses rather than 403s, so existence stays opaque.
    const plan = await repo.findById(req.orgId!, id);
    if (!plan) { reply.code(404); return { data: null, error: 'Load plan not found' }; }
    return { data: plan, error: null };
  });

  // POST /api/v1/load-plans — create from staged assignments
  server.post('/api/v1/load-plans', {
    schema: {
      tags: ['WMS - Load Planning'],
      summary: 'Create a load plan from staged assignments',
      body: {
        type: 'object', required: ['locationId', 'stagingAssignmentIds'],
        properties: {
          locationId: { type: 'string', format: 'uuid' },
          shipmentId: { type: 'string', nullable: true },
          dockBinId: { type: 'string', format: 'uuid', nullable: true },
          carrierId: { type: 'string', nullable: true },
          trailerNumber: { type: 'string', nullable: true },
          stagingAssignmentIds: { type: 'array', items: { type: 'string', format: 'uuid' }, minItems: 1 },
        },
      },
    },
  }, async (req: FastifyRequest, reply: FastifyReply) => {
    const body = z.object({
      locationId: z.string().uuid(),
      shipmentId: z.string().nullable().optional(),
      dockBinId: z.string().uuid().nullable().optional(),
      carrierId: z.string().nullable().optional(),
      trailerNumber: z.string().nullable().optional(),
      stagingAssignmentIds: z.array(z.string().uuid()).min(1),
    }).parse((req as any).body);

    const result = await commandBus.dispatch({
      type: CREATE_LOAD_PLAN, orgId: req.orgId!, actorId: req.user?.sub ?? null, payload: body,
      metadata: { correlationId: crypto.randomUUID(), source: 'api' },
    });

    if (!result.success) { reply.code(400); return { data: null, error: result.error }; }
    reply.code(201);
    return { data: result.data, error: null };
  });

  // POST /api/v1/load-plans/:id/complete — complete load plan, seal, generate BOL
  server.post('/api/v1/load-plans/:id/complete', {
    schema: {
      tags: ['WMS - Load Planning'],
      summary: 'Complete load plan: seal trailer, request BOL',
      body: {
        type: 'object',
        properties: {
          sealNumber: { type: 'string', nullable: true },
          generateBol: { type: 'boolean', description: 'Ask the transport side to generate a BOL (default: true). Generated asynchronously; the load plan carries bolDocumentId once it is ready' },
        },
      },
    },
  }, async (req: FastifyRequest, reply: FastifyReply) => {
    const { id } = req.params as { id: string };
    const body = z.object({
      sealNumber: z.string().nullable().optional(),
      generateBol: z.boolean().optional(),
    }).parse((req as any).body ?? {});

    const result = await commandBus.dispatch({
      type: COMPLETE_LOAD_PLAN, orgId: req.orgId!, actorId: req.user?.sub ?? null,
      payload: { loadPlanId: id, ...body },
      metadata: { correlationId: crypto.randomUUID(), source: 'api' },
    });

    if (!result.success) { reply.code(400); return { data: null, error: result.error }; }

    // The BOL is generated by a TMS subscriber on load_plan.completed, not here. The warehouse
    // does not own transport paperwork, and a WMS-only install has no subscriber at all.
    // bolDocumentId appears on the load plan once that finishes.
    return { data: result.data, error: null };
  });
}
