import { PrismaClient } from '@prisma/client';
import { PgBossEventBus } from '../../events/PgBossEventBus.js';
import { EVENT_TYPES } from '../../events/eventTypes.js';
import { BaseCommandHandler, TransactionClient, EmitFn } from '../BaseCommandHandler.js';
import { Command } from '../types.js';

export interface RotateWebhookSecretPayload {
  id: string;
  customerId: string;
  newSecret: string; // Generated by the route — this command doesn't pick the secret
}

export interface RotateWebhookSecretResult {
  id: string;
  /** Plaintext secret returned to the route so it can be shown to the customer once. */
  secret: string;
}

export const ROTATE_WEBHOOK_SECRET = 'customer_webhook.rotate_secret';

export class RotateWebhookSecretCommandHandler extends BaseCommandHandler<RotateWebhookSecretPayload, RotateWebhookSecretResult> {
  readonly commandType = ROTATE_WEBHOOK_SECRET;

  constructor(prisma: PrismaClient, eventBus: PgBossEventBus) {
    super(prisma, eventBus);
  }

  protected async handle(
    command: Command<RotateWebhookSecretPayload>,
    tx: TransactionClient,
    emit: EmitFn
  ): Promise<RotateWebhookSecretResult> {
    const { id, customerId, newSecret } = command.payload;

    const existing = await tx.customerWebhook.findUnique({ where: { id } });
    if (!existing || existing.customerId !== customerId) {
      throw new Error('Webhook not found');
    }

    const updated = await tx.customerWebhook.update({
      where: { id },
      data: { secret: newSecret },
    });

    // Secret never appears in the event payload — only the fact that
    // rotation occurred.
    emit(this.createEvent(command, {
      type: EVENT_TYPES.CUSTOMER_WEBHOOK_SECRET_ROTATED,
      entityType: 'customer_webhook',
      entityId: id,
      payload: { customerId, name: existing.name },
    }));

    return { id, secret: updated.secret };
  }
}
